name: farmhash
description: >-
  A Dart implementation of FarmHash.
homepage: https://github.com/smanilov/farmhash-dart
version: 0.0.1
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  fixnum: '>=0.10.11 <1.0.0'
dev_dependencies:
  test: '>=1.2.0 <2.0.0'
